feat: wrench model predictive controller on 2D spacecraft
Jaeyoung-Lim/px4-mpc pull request #15
Opened 2024-07-23 14:33 UTC by joris997

To complete a nice set of initial controllers, I've started on an MPC that publishes thrusts and torques (the wrench, separated over two publishers as per the PX4 message types).
Currently, the robot spins around its z-axis so I still need to fix that.

2024-07-23 16:38 UTC, Jaeyoung-Lim requested changes

2024-07-23 16:38 UTC, Jaeyoung-Lim commented on px4_mpc/px4_mpc/mpc_spacecraft.py
> +        rates_setpoint_msg.yaw = 0.0
We don't want to disable the rate publishing?

2024-07-23 16:39 UTC, Jaeyoung-Lim requested changes

2024-07-23 16:39 UTC, Jaeyoung-Lim commented on px4_mpc/px4_mpc/mpc_spacecraft.py
> +        self.mode = 'wrench'
Can you make this a parameter of the launchfile?

2024-07-23 16:40 UTC, Jaeyoung-Lim commented on px4_mpc/px4_mpc/mpc_spacecraft.py
> +        offboard_msg.acceleration = False
Redundant?

2024-07-23 16:40 UTC, Jaeyoung-Lim commented on px4_mpc/px4_mpc/controllers/spacecraft_wrench_mpc.py
> +#   Copyright (C) 2022 PX4 Development Team. All rights reserved.
```suggestion
#   Copyright (C) 2024 PX4 Development Team. All rights reserved.
```

2024-07-23 18:32 UTC, Pedro-Roque commented
@joris997 you might need to merge the latest master to your branch to make sure it is up to date.

2024-07-23 20:11 UTC, joris997 commented on px4_mpc/px4_mpc/mpc_spacecraft.py
> +        rates_setpoint_msg.yaw = 0.0
the rate publishing is never called upon. both rate and allocation functions remain but in the `cmdloop_callback` it is checked which publishers align to the controller mode.
The change here was actually due to a merge conflict that slipped through. It's now set to the original rates.

2024-07-24 06:13 UTC, Jaeyoung-Lim commented
> @joris997 you might need to merge the latest master to your branch to make sure it is up to date.

I would suggest a rebase

2024-07-26 14:13 UTC, Jaeyoung-Lim approved these changes
LGTM, thanks!

2024-07-26 14:13 UTC, merged

2024-07-26 14:14 UTC, Jaeyoung-Lim commented
@joris997 Could you add instructions on how to configure the different modes of the MPC?